/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;


import Modelo.Conexion;
import Modelo.ModelProductos;
import Modelo.Venta;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.DriverManager;
import java.util.ArrayList;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author algel
 */
public class JFrameMenu extends javax.swing.JFrame {
    //Agregar productos al combo
    String productos [] = {"---","Capuchino", " Frappé", "Americano"};
    int precios[] ={0,50,70,90}; //precios
    double precio=0;
    int cantidad=0;
    //tamaños
    String Tipotamanos [] = { "---" ,"CH", "M", "G"};
    //para agregar a la tabla
    DefaultTableModel modelo = new DefaultTableModel();
    ArrayList<Venta> listaVentas = new ArrayList<Venta>(); //guarda las ventas que se vayan realizando con los atributos de la clase Venta
    
    
    /**
     * Creates new form JFramePrueba
     */
    public JFrameMenu() {
        initComponents();
        this.setSize(new Dimension(800,550)); //tamano
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        //lo centra
        this.setLocale(null);
        //Titulo del Frame
        this.setTitle("Cafetería");
        Image icon= Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/IconCaf.png"));
        this.setIconImage(icon);
       
        //Muestra los tipos y nombres de los productos
        DefaultComboBoxModel comboModel = new DefaultComboBoxModel(productos);
        Combo_Producto.setModel(comboModel);
        DefaultComboBoxModel comboModel2 = new DefaultComboBoxModel(Tipotamanos);
        Combo_Tamano.setModel(comboModel2); // termina Muestra los tipos y nombres de los productos
        modelo.addColumn("Producto");
        modelo.addColumn("Tamaño");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Precio Unitario");
        modelo.addColumn("Total");
        
        
        
        //actualiza la tabla 
        actualizarTabla();
        //Calcula el precio
        calcuPrecio();
        
        //llenarProductos();
    
        //abre la ssegunda tabla (Detalle de venta)
        JFrameVenta tablaVenta= new JFrameVenta();
        tablaVenta.setVisible(true);
    
    }
    /*
    private void llenarProductos(){
        ModelProductos modProductos = new ModelProductos();
        ArrayList<Productos>listaProductos = modProductos.getProductos();
        
        
        Combo_Producto.removeAllItems(); //limpia el combobox
        Combo_Tamano.removeAllItems(); //limpia el combobox
        
        for(int i =0; i<listaProductos.size(); i++){
             Combo_Producto.addItem(listaProductos.get(i).getProducto());
        }
    } */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Total = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_Precio = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Combo_Producto = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnRealizarpedido = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_Productos = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lbl_Subtotal = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lbl_Iva = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn_Agregar = new javax.swing.JButton();
        Combo_Tamano = new javax.swing.JComboBox<>();
        sp_Cantidad = new javax.swing.JSpinner();
        jButton_FrameMenu1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Total.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_Total.setForeground(new java.awt.Color(0, 204, 255));
        lbl_Total.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_Total.setText("$0.00MXN");
        getContentPane().add(lbl_Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 460, 140, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Capuchino.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        lbl_Precio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_Precio.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Precio.setText("0.00");
        getContentPane().add(lbl_Precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 130, 40));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Taza");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 60, 20));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Copa");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 60, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Capuchino");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 100, 40));

        Combo_Producto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Combo_Producto.setForeground(new java.awt.Color(255, 255, 255));
        Combo_Producto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Combo_Producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo_ProductoActionPerformed(evt);
            }
        });
        getContentPane().add(Combo_Producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 120, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Vaso");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 60, 20));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Americano.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 60, 60));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Frappe.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 60, 60));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cantidad");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 70, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Producto");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 70, -1));

        btnRealizarpedido.setBackground(new java.awt.Color(51, 0, 0));
        btnRealizarpedido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRealizarpedido.setForeground(new java.awt.Color(0, 153, 153));
        btnRealizarpedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ordenar.png"))); // NOI18N
        btnRealizarpedido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRealizarpedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarpedidoActionPerformed(evt);
            }
        });
        getContentPane().add(btnRealizarpedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, 70, 60));

        tab_Productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Producto", "Tamaño", "Precio", "Cantidad"
            }
        ));
        tab_Productos.setEnabled(false);
        jScrollPane1.setViewportView(tab_Productos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 460, 170));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Regresar");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Tamaño");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 60, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Agregar Producto");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 170, 40));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 204, 255));
        jLabel20.setText("Detalles del Pedido");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, 190, 40));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 204, 255));
        jLabel21.setText("Total:");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 460, 60, 40));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 204, 255));
        jLabel22.setText("SubTotal:");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 390, 100, 40));

        lbl_Subtotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_Subtotal.setForeground(new java.awt.Color(0, 204, 255));
        lbl_Subtotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_Subtotal.setText("$0.00MXN");
        getContentPane().add(lbl_Subtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 390, 130, 40));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Realizar Pedido");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 160, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Americano");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 100, 40));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 204, 255));
        jLabel23.setText("IVA:");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, 50, 40));

        lbl_Iva.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_Iva.setForeground(new java.awt.Color(0, 204, 255));
        lbl_Iva.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_Iva.setText("$0.00MXN");
        getContentPane().add(lbl_Iva, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 430, 140, 40));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Frappé");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 100, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Precio");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 60, -1));

        btn_Agregar.setBackground(new java.awt.Color(51, 0, 0));
        btn_Agregar.setForeground(new java.awt.Color(51, 0, 0));
        btn_Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Agrgear_Producto.png"))); // NOI18N
        btn_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, 100, 60));

        Combo_Tamano.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Combo_Tamano.setForeground(new java.awt.Color(255, 255, 255));
        Combo_Tamano.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----", "CH", "M", "G" }));
        Combo_Tamano.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Combo_Tamano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo_TamanoActionPerformed(evt);
            }
        });
        getContentPane().add(Combo_Tamano, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 70, -1));

        sp_Cantidad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sp_Cantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        sp_Cantidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sp_CantidadStateChanged(evt);
            }
        });
        getContentPane().add(sp_Cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 60, 30));

        jButton_FrameMenu1.setBackground(new java.awt.Color(51, 0, 0));
        jButton_FrameMenu1.setForeground(new java.awt.Color(51, 0, 0));
        jButton_FrameMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Regresar.png"))); // NOI18N
        jButton_FrameMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_FrameMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FrameMenu1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_FrameMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 60, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Fon1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Fon1.jpg"))); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 630, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Fon1.jpg"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 610, 340));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Fon1.jpg"))); // NOI18N
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 130, -1, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRealizarpedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarpedidoActionPerformed
        //anda a llamar el Frame menuPrincipal
        Conexion mConexion;
        int FilaSeleccionada=tab_Productos.getSelectedRow();
        if(FilaSeleccionada>=0){
            String Datos[]=new String[2];
            Datos[0]=tab_Productos.getValueAt(FilaSeleccionada,0).toString();
            Datos[1]=tab_Productos.getValueAt(FilaSeleccionada,1).toString();
            Datos[2]=tab_Productos.getValueAt(FilaSeleccionada,1).toString();
            Datos[3]=tab_Productos.getValueAt(FilaSeleccionada,1).toString();
            
            
            JFrameVenta.modelo2.addRow(Datos);
            modelo.removeRow(FilaSeleccionada);
        }
        
        for(int i =0; i<tab_Productos.getRowCount(); i++){
            String Datos[] = new String[4];
            Datos[0]=tab_Productos.getValueAt(i, 0).toString();
            Datos[1]=tab_Productos.getValueAt(i, 1).toString();
            Datos[2]=tab_Productos.getValueAt(i, 2).toString();
            Datos[3]=tab_Productos.getValueAt(i, 3).toString();
            
            JFrameVenta.modelo2.addRow(Datos);
        }
        
        DefaultTableModel tblModel = (DefaultTableModel) tab_Productos.getModel();
        if(tblModel.getRowCount()==0){
            JOptionPane.showMessageDialog(this, "No hay ventas");
            
        }else{
            try {
                //si  la tabla no es vacia
                Class.forName("com.mysql.cj.jdbc.Driver");
                 mConexion = new Conexion("cafeteria","root", "");
                for(int i=0;i<tblModel.getRowCount();i++){
                    
                    String query ="insert into venta(idventa, productos, tamano,cantidad,precio,total)values(?,?,?,?,?,?)"; 
                    
                
                }    
            } catch (Exception e) {
                
            }
        }
    }//GEN-LAST:event_btnRealizarpedidoActionPerformed

    private void jButton_FrameMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_FrameMenu1ActionPerformed
        // TODO add your handling code here:
        //manda a llamar el frame menú principal
        menuPrincipal interMenu = new  menuPrincipal(); //se agrega un nuevo objeto
        interMenu.setVisible(true); //hace que sea visible el frame que se llama
        this.dispose(); //se elimina este frame al regresar al anterior
    }//GEN-LAST:event_jButton_FrameMenu1ActionPerformed

    private void Combo_ProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo_ProductoActionPerformed
        // TODO add your handling code here:
        
        calcuPrecio();
    }//GEN-LAST:event_Combo_ProductoActionPerformed

    private void Combo_TamanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo_TamanoActionPerformed
        // TODO add your handling code here:
       // String tamano = (String) Combo_Tamano.getSelectedItem();
        //
        calcuPrecio();
    }//GEN-LAST:event_Combo_TamanoActionPerformed

    private void sp_CantidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sp_CantidadStateChanged
        // TODO add your handling code here:
        calcuPrecio();
    }//GEN-LAST:event_sp_CantidadStateChanged

    private void btn_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AgregarActionPerformed
        // TODO add your handling code here:
       
        Venta venta = new Venta();
        venta.setId(Combo_Producto.getSelectedIndex());
        venta.setProducto(Combo_Producto.getSelectedItem().toString());
        venta.setId(Combo_Tamano.getSelectedIndex());
        venta.setTipotamano(Combo_Tamano.getSelectedItem().toString());
        venta.setPrecio(precio);
        venta.setCantidad(cantidad);
        venta.setPrecio(precio*cantidad);
        //venta.setTotal(Moneda(total));
        if(!buscarVenta( venta)){ //solo agrega a la lista de ventas un producto
            listaVentas.add(venta); // que no haya sido agregado a la lista
            
        }
        
        actualizarTabla();
        borrarVenta();
    }//GEN-LAST:event_btn_AgregarActionPerformed
    
    //Si ya está agregado un producto a la lista de ventas, este método, actualiza la cantidad del prodcuto e importe
    public boolean buscarVenta(Venta nueva){
        for(Venta v : listaVentas){
                if(v.getId()==nueva.getId()){
                    int nuevaCantidad=v.getCantidad()+nueva.getCantidad();
                    v.setCantidad(nuevaCantidad);
                    v.setPrecio(v.getPrecio()*nuevaCantidad);
                    return true; //si encuentra la venta retorna un true
                }
            }
        return false; //si no encuentra la venta retorna un false 
    }
    
    public void borrarVenta(){
        precio= 0;
        cantidad = 1;
        sp_Cantidad.setValue(1);
        calcuPrecio();
    }
    public void calcuPrecio(){
        //Da el precio de acuerdo a lo que se tenga seleccionado en el combobox
        precio= precios [Combo_Producto.getSelectedIndex()];
        precio= precios [Combo_Tamano.getSelectedIndex()]; //termina
        //lo que se tenga en  sp_cantidada lo convierte a int
        cantidad = Integer.parseInt(sp_Cantidad.getValue().toString());
        lbl_Precio.setText(Moneda(precio)); //el lbl_precio recibe el precio
        lbl_Precio.setText(Moneda(precio*cantidad));
    }
    
    //REcibe el precio establecido y regresa un String
    public String Moneda(double precio){
        return "$ " + Math.round(precio*100.0)/100.0+ "MNX"; //Lo redondea a uno a 2 decmales
    }
    
    //Actualizar Tabla
    public void actualizarTabla(){
        while(modelo.getRowCount()>0){
            modelo.removeRow(0);
        }
        double subtotal=0;
        for(Venta v : listaVentas){ //acamoda los valores en la tabla
            Object x []= new Object[4];
            x[0]=v.getProducto();
            x[1]=v.getTipotamano();
            x[2]=v.getCantidad();
            x[3]=Moneda(v.getPrecio());
            //x[4]=Moneda(v.getTotal());
            subtotal+=v.getPrecio();
            modelo.addRow(x);  
        }
        double iva=subtotal*0.16; //valor del IVA
        double total=subtotal+iva;
        lbl_Subtotal.setText(Moneda(subtotal)); //muestra el subtotal
        lbl_Iva.setText(Moneda(iva)); //muestra el iva
        lbl_Total.setText(Moneda(total)); //muestra el total
        
        tab_Productos.setModel(modelo);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Combo_Producto;
    private javax.swing.JComboBox<String> Combo_Tamano;
    private javax.swing.JButton btnRealizarpedido;
    private javax.swing.JButton btn_Agregar;
    private javax.swing.JButton jButton_FrameMenu1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Iva;
    private javax.swing.JLabel lbl_Precio;
    private javax.swing.JLabel lbl_Subtotal;
    private javax.swing.JLabel lbl_Total;
    private javax.swing.JSpinner sp_Cantidad;
    private javax.swing.JTable tab_Productos;
    // End of variables declaration//GEN-END:variables
}
